### PR TITLE
Sphinx docs

### PR DESCRIPTION
**Pull request by svenkreiss**
Documentation build is automated with a Github service and available here:
http://s2sphere.readthedocs.org/en/sphinx-docs/index.html

---
This change is [Reviewable](https://reviewable.io/reviews/sidewalklabs/sphere/2)

### CODE REVIEW

**Comment by danvk** [comment]
What do popular Python projects do in terms of committing generated Sphinx files to their repos?

---

Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/sphinx/api.rst, line 1 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/2#-KFufSktHbceDFFtvlVN:-KFufSktHbceDFFtvlVO:-1046475053) ([raw file](https://github.com/sidewalklabs/sphere/blob/93bac1b285cd311ce0dabf522ba8ddd222b01855/docs/sphinx/api.rst#L1)):*
Is this normal to commit the generated docs to the git repo? Does readthedocs pull them from GitHub or from PyPI releases?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/sphere/2#-:-KFugYyX14OadGi7N9mw:1923209873)*

**Comment by svenkreiss** [comment]
Generated docs are not included. They are in an `_build` directory that is in `.gitignore`.

---

Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[docs/sphinx/api.rst, line 1 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/2#-KFufSktHbceDFFtvlVN:-KFugwQc_u5dx8A0OKCE:1916738305) ([raw file](https://github.com/sidewalklabs/sphere/blob/93bac1b285cd311ce0dabf522ba8ddd222b01855/docs/sphinx/api.rst#L1)):*
This is not the generated part. I added this list by hand. I think we want to fine tune (or prune) this list to what we consider being a "public" API.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/sphere/2#-:-KFuhDlxD3Feus5Ukbqp:-522446302)*

**Comment by danvk** [comment]
Yeah, I guess I meant more the `Makefile` and `conf.py` files which look auto-generated. Do we want to include those?

---

Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/sphere/2#-:-KFui5TRv7JD2Nuvb16Z:-254135724)*

**Comment by svenkreiss** [comment]
They are generated by running `sphinx-quickstart` but then modified by hand. They need to be included.

---

Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/sphere/2#-:-KFuiMAduw0wv801RERM:873814405)*

**Comment by danvk** [comment]
:lgtm:

---

Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/sphere/2#-:-KFuiwt3mV5qpBUT38bQ:1417088721)*

**Pull request merged**
