### PR TITLE
package structure, performance, TravisCI, Python 3

### PR DESCRIPTION
**Pull request by svenkreiss**
* simplified package structure
* performance improvements
* Python 3 updates for RegionCoverer
* continuous tests with TravisCI
* option to run tests with `cProfile`
* add original s2-geometry library for test references
* extended README; converted from `md` to `rst` for PyPI

---
This change is [Reviewable](https://reviewable.io/reviews/sidewalklabs/sphere/1)

### CODE REVIEW

**Comment by danvk** [comment]
Left a bunch of comments but nothing major. Looking good!

---

Review status: 0 of 11 files reviewed at latest revision, 20 unresolved discussions.

---

*[.travis.yml, line 16 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoK0_f1vgmrI95kQBw:-KFoK0_f1vgmrI95kQBx:-961802366) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/.travis.yml#L16)):*
It would be good to run the tests with both Python 2 and Python 3 to ensure compatibility with both.

---

*[README.rst, line 1 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoGRdi-YjPokej4v3Q:-KFoGRdi-YjPokej4v3R:1747097172) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/README.rst#L1)):*
So PyPI requires `rst` files? Is it possible to write a `README.md` file like our other projects and convert it when we submit to PyPI?

---

*[README.rst, line 23 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoGzWva9Xvzuqzovgc:-KFoGzWva9Xvzuqzovgd:-1865985359) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/README.rst#L23)):*
Where will the docs eventually live? We've each worked through a few examples of how to do concrete tasks using `s2sphere` and we should include all of those in the documentation.

---

*[README.rst, line 27 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoGj4-G5hKAB7ecSpm:-KFoGj4-G5hKAB7ecSpn:-117780260) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/README.rst#L27)):*
Code below might be more readable with:

```python
from s2sphere import (RegionCoverer, LatLon, LatLonRect)
```

---

*[README.rst, line 74 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoJtVsKauZYcMVg48u:-KFoJtVtF3OCGhLfc6KP:135588875) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/README.rst#L74)):*
Put these two commands in a code block for easier copy/pasting.

---

*[README.rst, line 81 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoHJ0NgMxVN3QsUE5G:-KFoHJ0NgMxVN3QsUE5H:1542525708) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/README.rst#L81)):*
Do you agree with this?

---

*[s2sphere/sphere.py, line 49 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoHalwrhWXItCFG251:-KFoHalwrhWXItCFG252:2016981397) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/s2sphere/sphere.py#L49)):*
TODO (not for this PR): port over comments from the C++ classes as docstrings.

---

*[s2sphere/sphere.py, line 864 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoKP35deiLJopXt763:-KFoKP35deiLJopXt764:-1599863565) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/s2sphere/sphere.py#L864)):*
So did the `int()` really wind up being the bottleneck? I'm still confused as to why that would be.

---

*[s2sphere/sphere.py, line 876 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoI3VmbcDBBvr8hW8g:-KFoI3VmbcDBBvr8hW8h:-1445232876) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/s2sphere/sphere.py#L876)):*
`return not self.__eq__(other)`?

---

*[s2sphere/sphere.py, line 1228 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoHnJYMU0QORGrqvE9:-KFoHnJYMU0QORGrqvEA:-1838834133) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/s2sphere/sphere.py#L1228)):*
Docstrings usually have a short summary on the first line, then a blank, then details, right?

```python
'''Return the neighbors of closest vertex to this cell at the given level.

Normally there are four neighbors, but the closest vertex may only have
three neighbors if it is one of the 8 cube vertices.
'''
```

---

*[tests/compare_implementations_test.py, line 13 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoIKevNLqPtOIhnJwg:-KFoIKevNLqPtOIhnJwh:-977678214) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/tests/compare_implementations_test.py#L13)):*
Does `c` == `cell_id` here? May as well spell it out.

---

*[tests/compare_implementations_test.py, line 19 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoIQyBo9-KvtwE-NtJ:-KFoIQyBo9-KvtwE-NtK:677591412) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/tests/compare_implementations_test.py#L19)):*
drop

---

*[tests/compare_implementations_test.py, line 22 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoIVS5maX9enKTbii6:-KFoIVS5maX9enKTbii7:2108683644) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/tests/compare_implementations_test.py#L22)):*
Can `level` be set from the command line? Suggest either killing it or looping over all the levels for a more rigorous test.

---

*[tests/compare_implementations_test.py, line 30 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoIRumFcPngq2E9V_k:-KFoIRumFcPngq2E9V_l:677591412) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/tests/compare_implementations_test.py#L30)):*
drop

---

*[tests/covering_test.py, line 21 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoJDOAZj2Gthv8IWEe:-KFoIopWhLLzNtK899PC:1798392523) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/tests/covering_test.py#L21)):*
Can you drop this if you do:

```python
self.assertEquals(ids, target)
```

i.e. will it print the two items if they don't match? (It's nice to keep test output from getting noisy.)

---

*[tests/sphere_test.py, line 20 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoL1Gu-4ClJ4Q5vfaG:-KFoL1Gu-4ClJ4Q5vfaH:-371948989) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/tests/sphere_test.py#L20)):*
Either delete, uncomment or add a comment indicating why this differs from the C++ tests.

---

*[tests/sphere_test.py, line 30 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoKtnTqWmp9GcU-Lfn:-KFoKtnTqWmp9GcU-Lfo:854370365) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/tests/sphere_test.py#L30)):*
You should add some comments while you understand what these are—assuming you understand what these are :)

---

*[tests/sphere_test.py, line 298 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoM7YLIcKV5n46dgr8:-KFoM7YLIcKV5n46dgr9:1702379862) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/tests/sphere_test.py#L298)):*
just delete this if it's unused.

---

*[tests/sphere_test.py, line 473 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoLHcmTROecgxS0lQh:-KFoLHcmTROecgxS0lQi:1072745952) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/tests/sphere_test.py#L473)):*
`pr` → `profile` (here and elsewhere)

---

*[tests/sphere_test.py, line 2063 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoLcXIapTdMK0wuZs6:-KFoLcXIapTdMK0wuZs7:1702495726) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/tests/sphere_test.py#L2063)):*
uncomment or add a comment explaining why this is disabled.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-:-KFoMqDVgMjXjw5ecXFC:-897458556)*

**Comment by svenkreiss** [comment]
Review status: 0 of 11 files reviewed at latest revision, 19 unresolved discussions.

---

*[.travis.yml, line 16 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoK0_f1vgmrI95kQBw:-KFtCStKrN7xeawiwe2_:-450920897) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/.travis.yml#L16)):*
This turned out to be relatively difficult but done now.

---

*[README.rst, line 1 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoGRdi-YjPokej4v3Q:-KFtAgzC9KrozJwzOaKK:-1491693819) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/README.rst#L1)):*
I would like to keep it as `rst`. Sphinx docs will also be in `rst`.

---

*[README.rst, line 23 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoGzWva9Xvzuqzovgc:-KFtAwCM809LWkFZfEXH:-1647369952) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/README.rst#L23)):*
Coming up in the next PR. There will be a `docs/sphinx` folder containing the documentation (with code comment extraction). ReadTheDocs will read this configuration and build and host the documentation.

---

*[README.rst, line 27 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoGj4-G5hKAB7ecSpm:-KFtBOkH4c2GHHPiBVKp:-892458054) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/README.rst#L27)):*
In this particular example, yes it would look nicer. But it is generally considered better style to keep the module names for references to external packages. It is different for internal imports like a hypothetical `latlon.py` doing `from point import Point`.

---

*[README.rst, line 74 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoJtVsKauZYcMVg48u:-KFtCGAx4ZN_v4S7Izxh:1490519276) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/README.rst#L74)):*
you can copy and paste those.

---

*[README.rst, line 81 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoHJ0NgMxVN3QsUE5G:-KFtCJqWaahTUj_tZc17:-753352637) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/README.rst#L81)):*
No. And I don't think a README file is a good place for this. Removed.

---

*[s2sphere/sphere.py, line 864 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoKP35deiLJopXt763:-KFtPJ16HeBjyAAhOqqm:-1963637447) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/s2sphere/sphere.py#L864)):*
Yes. I was surprised too that it is such an overhead.

---

*[s2sphere/sphere.py, line 876 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoI3VmbcDBBvr8hW8g:-KFtRgcWAMWefjPYrrmR:-1741779215) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/s2sphere/sphere.py#L876)):*
good catch. Done

---

*[s2sphere/sphere.py, line 1228 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoHnJYMU0QORGrqvE9:-KFtRfRPKXghnvJjnEyA:-499146009) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/s2sphere/sphere.py#L1228)):*
Done.

---

*[tests/compare_implementations_test.py, line 13 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoIKevNLqPtOIhnJwg:-KFtUIXNMi_YI4zm4qR3:-499146009) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/tests/compare_implementations_test.py#L13)):*
Done.

---

*[tests/compare_implementations_test.py, line 19 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoIQyBo9-KvtwE-NtJ:-KFtUJk_boaAu0W3Fo-g:-499146009) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/tests/compare_implementations_test.py#L19)):*
Done.

---

*[tests/compare_implementations_test.py, line 22 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoIVS5maX9enKTbii6:-KFtRaG-Lz8vhVr1wwKW:-499146009) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/tests/compare_implementations_test.py#L22)):*
Done.

---

*[tests/compare_implementations_test.py, line 30 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoIRumFcPngq2E9V_k:-KFtRZ6gozqv3YS51_qF:-499146009) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/tests/compare_implementations_test.py#L30)):*
Done.

---

*[tests/covering_test.py, line 21 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoJDOAZj2Gthv8IWEe:-KFtRc8VHOOhA0Lemgyl:-499146009) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/tests/covering_test.py#L21)):*
Done.

---

*[tests/sphere_test.py, line 20 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoL1Gu-4ClJ4Q5vfaG:-KFtULW3u8E_CzYu-apk:-499146009) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/tests/sphere_test.py#L20)):*
Done.

---

*[tests/sphere_test.py, line 30 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoKtnTqWmp9GcU-Lfn:-KFtUF3fXz9OsfGeD9qL:-499146009) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/tests/sphere_test.py#L30)):*
Done.

---

*[tests/sphere_test.py, line 298 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoM7YLIcKV5n46dgr8:-KFtSCsUUwcjquUWDVVi:-499146009) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/tests/sphere_test.py#L298)):*
Done.

---

*[tests/sphere_test.py, line 473 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoLHcmTROecgxS0lQh:-KFtSN6tmvwwBIUybdOR:-499146009) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/tests/sphere_test.py#L473)):*
Done.

---

*[tests/sphere_test.py, line 2063 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoLcXIapTdMK0wuZs6:-KFtSgH0RcHkdIkzDozL:-499146009) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/tests/sphere_test.py#L2063)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/sphere/1)*

**Comment by danvk** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[.travis.yml, line 57 \[r2\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFtnbJZ4Qa4oeV9Vo2o:-KFtnbJ_kCPbC2AmY51k:863718100) ([raw file](https://github.com/sidewalklabs/sphere/blob/e1e345395ee4d4650418ff77eddda54d23a71e94/.travis.yml#L57)):*
Why the double quotes around this?

---

*[README.rst, line 74 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoJtVsKauZYcMVg48u:-KFtntXoPtTx29Rkv-tf:647982127) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/README.rst#L74)):*
It's two copy/pastes instead of one, though. I think this reads as "here's some magic you need to run to make this work" and most readers won't care too much about why it works, just that it does.

I don't care too much either way.

---

*[setup.py, line 22 \[r2\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFtoI8-t_czSf5PSm7C:-KFtoI80jW4mqt-f7D9y:-808375442) ([raw file](https://github.com/sidewalklabs/sphere/blob/e1e345395ee4d4650418ff77eddda54d23a71e94/setup.py#L22)):*
Do we still need to specifically install these in `.travis.yml` and mention them in the `README.rst` file now that this is here? What does this do?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-:-KFtojOgwa9oZxIa077G:1417088721)*

**Comment by svenkreiss** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis.yml, line 57 \[r2\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFtnbJZ4Qa4oeV9Vo2o:-KFts2LFodBk9H5-aPIt:1926193510) ([raw file](https://github.com/sidewalklabs/sphere/blob/e1e345395ee4d4650418ff77eddda54d23a71e94/.travis.yml#L57)):*
because it would allow for `pip install --user .[tests]` but that is not used anymore

---

*[README.rst, line 74 \[r1\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFoJtVsKauZYcMVg48u:-KFtrOkMtbbefGjLBmle:663875586) ([raw file](https://github.com/sidewalklabs/sphere/blob/48cc437564a40bfa664c99c65d7f8b886b374c57/README.rst#L74)):*
you cannot just copy both commands. The first one yes, but the second one needs to be used where the comment is in the code block of the install instructions. Let's keep it like this. This is only for developers.

---

*[setup.py, line 22 \[r2\]](https://reviewable.io:443/reviews/sidewalklabs/sphere/1#-KFtoI8-t_czSf5PSm7C:-KFtrjw_BUfR0Fn0maGd:1151637785) ([raw file](https://github.com/sidewalklabs/sphere/blob/e1e345395ee4d4650418ff77eddda54d23a71e94/setup.py#L22)):*
In new versions of pip, you can do `pip install .[tests]` to install the dependencies given here. However, that does not seem to work on Travis under OSX even with a pip update.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sidewalklabs/sphere/1)*

**Pull request merged**
